Add Alpine build-base package in build stage
It seems to be needed since golang v1.19 for linux/386 architecture.

Otherwise:

```
runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
------
Error: failed to solve: process "/bin/sh -c tar xf src.tgz --strip 1 && go build -o azcopy  && ./azcopy --version" did not complete successfully: exit code: 2
```